### PR TITLE
Build binaries automatically using GitHub Actions

### PR DESCRIPTION
**Pull request by pilattebe**
Currently macOS and Windows are running. To access the binaries of a commit:
1. Go to the Actions tab and Click on a commit
Screen Shot 2021-01-17 at 01 13 48
2. Go to the bottom of the page and download the artifact for your platform
Screen Shot 2021-01-17 at 01 14 24

windows is not supported because I wasn't able to install libpcre

### CODE REVIEW

**Comment by pilattebe** [comment]
If you figure out how to install libpcre on windows via command-line, I will add windows support.

**Comment by pilattebe** [comment]
I've not tested the binaries yet.

**Comment by marhop** [comment]
Looks great, thank your very much! (I will probably reuse this setup in other projects as well, so that's double useful.) I hope you didn't neglect your exams too much for this?

The Linux binary works for me. Please let me know when you tested the MacOS binary! I'll have a look at the Windows stuff.

**Comment by pilattebe** [comment]
1. No, I finished my exams on Friday, I did this after, as promised.
2. macOS binary is running fine (when run with the corresponding pandoc version).
3. I think I left windows setup commented out in the yaml file if you want to take a look
4. The Actions are run on every commits on master (this can be changed)
5. You can have a GitHub Actions setup to automatically do a release and publish binaries but I don't understand it yet
6. The default Github Haskell yaml setup is a waste of time, It runs on deprecated versions of everything and you have to go fix their stuff
7. 99% of the uptime of the vm is spent compiling dependencies, I think there is a better way but all this VM time is free for public repos so I don't know if I care enough to want to fix it as caching would introduce more bug than it solves.

**Comment by marhop** [comment]
> 1. No, I finished my exams on Friday, I did this after, as promised.

👍

> 5. You can have a GitHub Actions setup to automatically do a release and publish binaries but I don't understand it yet

Yeah, I read about that too somewhere but it sounded like more hassle than use. (At least in this case.)
 
> 7. 99% of the uptime of the vm is spent compiling dependencies, I think there is a better way but all this VM time is free for public repos so I don't know if I care enough to want to fix it as caching would introduce more bug than it solves.

Sounds reasonable. 😄

**Pull request merged**
